[settings]
experimental = true

[tools]
deno = "latest"
node = "lts"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
# Aqua managed tools
"aqua:arduino/arduino-language-server" = "latest"
"aqua:aristocratos/btop" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:cli/cli" = "latest"
"aqua:cloudflare/cloudflared" = "latest"
"aqua:eza-community/eza" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:nektos/act" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:rhysd/actionlint" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:tombi-toml/tombi" = "latest"
"aqua:twpayne/chezmoi" = "latest"
"aqua:volta-cli/volta" = "latest"
"aqua:ynqa/jnv" = "latest"
# Github based tools
"github:docker/docker-language-server" = "latest"
"github:terror/just-lsp" = "latest"
# Node.js based tools
"npm:@bitwarden/cli" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@himorishige/hatago-mcp-hub" = "latest"
"npm:basedpyright" = "latest"
"npm:bash-language-server" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:neovim" = "latest"
"npm:pyright" = "latest"
"npm:semver" = "latest"
"npm:svelte-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vim-language-server" = "latest"
"npm:yaml-language-server" = "latest"
# Python based tools
"pipx:black" = "latest"
"pipx:cmake-language-server" = "latest"
"pipx:flake8" = "latest"
"pipx:ignr" = "latest"
"pipx:isort" = "latest"
"pipx:mypy" = "latest"
"pipx:ruff" = "latest"
"pipx:yt-dlp" = "latest"
